# Generated by Django 4.0 on 2022-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='email_auth_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='password_reset_auth_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
