# Generated by Django 4.0 on 2022-01-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_extendeduser_email_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email_verification_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
