# Generated by Django 4.0 on 2022-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_extendeduser_email_verification_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='email_auth_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
